export const TICKET_REQUEST = "TICKET_REQUEST";
export const TICKET_SUCCESS = "TICKET_SUCCESS";
export const TICKET_FAIL = "TICKET_FAIL";
export const TICKET_INTERACT_REQUEST = "TICKET_INTERACT_REQUEST";
export const TICKET_INTERACT_SUCCESS = "TICKET_INTERACT_SUCCESS";
export const TICKET_INTERACT_FAIL = "TICKET_INTERACT_FAIL";
export const TICKET_COMPLETE_INTERACT_REQUEST =
  "TICKET_COMPLETE_INTERACT_REQUEST";
export const TICKET_COMPLETE_INTERACT_SUCCESS =
  "TICKET_COMPLETE_INTERACT_SUCCESS";
export const TICKET_COMPLETE_INTERACT_FAIL = "TICKET_COMPLETE_INTERACT_FAIL";
